INSERT INTO `destinations` (`id`, `name`,`description`) VALUES
(1, 'Afghanistan','Descripcion de Afghanistan'),
(2, 'Aland Islands','Descripcion de Aland Islands'),
(3, 'Albania','Descripcion de Albania'),
(4, 'Algeria','Descripcion de Algeria'),
(5, 'American Samoa','Descripcion de American Samoa'),
(6, 'Andorra','Descripcion de Andorra'),
(7, 'Angola','Descripcion de Angola'),
(8, 'Anguilla','Descripcion de Anguilla'),
(9, 'Antarctica','Descripcion de Antarctica'),
(10, 'Antigua and Barbuda','Descripcion de Antigua and Barbuda'),
(11, 'Argentina','Descripcion de Argentina'),
(12, 'Armenia','Descripcion de Armenia'),
(13, 'Aruba','Descripcion de Aruba'),
(14, 'Australia','Descripcion de Australia'),
(15, 'Austria','Descripcion de Austria'),
(16, 'Azerbaijan','Descripcion de Azerbaijan'),
(17, 'Bahamas','Descripcion de Bahamas'),
(18, 'Bahrain','Descripcion de Bahrain'),
(19, 'Bangladesh','Descripcion de Bangladesh'),
(20, 'Barbados','Descripcion de Barbados'),
(21, 'Belarus','Descripcion de Belarus'),
(22, 'Belgium','Descripcion de Belgium'),
(23, 'Belize','Descripcion de Belize'),
(24, 'Benin','Descripcion de Benin'),
(25, 'Bermuda','Descripcion de Bermuda'),
(26, 'Bhutan','Descripcion de Bhutan'),
(27, 'Bolivia','Descripcion de Bolivia'),
(28, 'Bonaire, Sint Eustatius and Saba','Descripcion de Bonaire, Sint Eustatius and Saba'),
(29, 'Bosnia and Herzegovina','Descripcion de Bosnia and Herzegovina'),
(30, 'Botswana','Descripcion de Botswana'),
(31, 'Bouvet Island','Descripcion de Bouvet Island'),
(32, 'Brazil','Descripcion de Brazil'),
(33, 'British Indian Ocean Territory','Descripcion de British Indian Ocean Territory'),
(34, 'Brunei Darussalam','Descripcion de Brunei Darussalam'),
(35, 'Bulgaria','Descripcion de Bulgaria'),
(36, 'Burkina Faso','Descripcion de Burkina Faso'),
(37, 'Burundi','Descripcion de Burundi'),
(38, 'Cambodia','Descripcion de Cambodia'),
(39, 'Cameroon','Descripcion de Cameroon'),
(40, 'Canada','Descripcion de Canada'),
(41, 'Cape Verde','Descripcion de Cape Verde'),
(42, 'Cayman Islands','Descripcion de Cayman Islands'),
(43, 'Central African Republic','Descripcion de Central African Republic'),
(44, 'Chad','Descripcion de Chad'),
(45, 'Chile','Descripcion de Chile'),
(46, 'China','Descripcion de China'),
(47, 'Christmas Island','Descripcion de Christmas Island'),
(48, 'Cocos (Keeling) Islands','Descripcion de Cocos (Keeling) Islands'),
(49, 'Colombia','Descripcion de Colombia'),
(50, 'Comoros','Descripcion de Comoros'),
(51, 'Congo','Descripcion de Congo'),
(52, 'Congo, Democratic Republic of the Congo','Descripcion de Congo, Democratic Republic of the Congo'),
(53, 'Cook Islands','Descripcion de Cook Islands'),
(54, 'Costa Rica','Descripcion de Costa Rica'),
(55, 'Cote D\'Ivoire','Descripcion de Cote D\'Ivoire'),
(56, 'Croatia','Descripcion de Croatia'),
(57, 'Cuba','Descripcion de Cuba'),
(58, 'Curacao','Descripcion de Curacao'),
(59, 'Cyprus','Descripcion de Cyprus'),
(60, 'Czech Republic','Descripcion de Czech Republic'),
(61, 'Denmark','Descripcion de Denmark'),
(62, 'Djibouti','Descripcion de Djibouti'),
(63, 'Dominica','Descripcion de Dominica'),
(64, 'Dominican Republic','Descripcion de Dominican Republic'),
(65, 'Ecuador','Descripcion de Ecuador'),
(66, 'Egypt','Descripcion de Egypt'),
(67, 'El Salvador','Descripcion de El Salvador'),
(68, 'Equatorial Guinea','Descripcion de Equatorial Guinea'),
(69, 'Eritrea','Descripcion de Eritrea'),
(70, 'Estonia','Descripcion de Estonia'),
(71, 'Ethiopia','Descripcion de Ethiopia'),
(72, 'Falkland Islands (Malvinas)','Descripcion de Falkland Islands (Malvinas)'),
(73, 'Faroe Islands','Descripcion de Faroe Islands'),
(74, 'Fiji','Descripcion de Fiji'),
(75, 'Finland','Descripcion de Finland'),
(76, 'France','Descripcion de France'),
(77, 'French Guiana','Descripcion de French Guiana'),
(78, 'French Polynesia','Descripcion de French Polynesia'),
(79, 'French Southern Territories','Descripcion de French Southern Territories'),
(80, 'Gabon','Descripcion de Gabon'),
(81, 'Gambia','Descripcion de Gambia'),
(82, 'Georgia','Descripcion de Georgia'),
(83, 'Germany','Descripcion de Germany'),
(84, 'Ghana','Descripcion de Ghana'),
(85, 'Gibraltar','Descripcion de Gibraltar'),
(86, 'Greece','Descripcion de Greece'),
(87, 'Greenland','Descripcion de Greenland'),
(88, 'Grenada','Descripcion de Grenada'),
(89, 'Guadeloupe','Descripcion de Guadeloupe'),
(90, 'Guam','Descripcion de Guam'),
(91, 'Guatemala','Descripcion de Guatemala'),
(92, 'Guernsey','Descripcion de Guernsey'),
(93, 'Guinea','Descripcion de Guinea'),
(94, 'Guinea-Bissau','Descripcion de Guinea-Bissau'),
(95, 'Guyana','Descripcion de Guyana'),
(96, 'Haiti','Descripcion de Haiti'),
(97, 'Heard Island and Mcdonald Islands','Descripcion de Heard Island and Mcdonald Islands'),
(98, 'Holy See (Vatican City State)','Descripcion de Holy See (Vatican City State)'),
(99, 'Honduras','Descripcion de Honduras'),
(100, 'Hong Kong','Descripcion de Hong Kong'),
(101, 'Hungary','Descripcion de Hungary'),
(102, 'Iceland','Descripcion de Iceland'),
(103, 'India','Descripcion de India'),
(104, 'Indonesia','Descripcion de Indonesia'),
(105, 'Iran, Islamic Republic of','Descripcion de Iran, Islamic Republic of'),
(106, 'Iraq','Descripcion de Iraq'),
(107, 'Ireland','Descripcion de Ireland'),
(108, 'Isle of Man','Descripcion de Isle of Man'),
(109, 'Israel','Descripcion de Israel'),
(110, 'Italy','Descripcion de Italy'),
(111, 'Jamaica','Descripcion de Jamaica'),
(112, 'Japan','Descripcion de Japan'),
(113, 'Jersey','Descripcion de Jersey'),
(114, 'Jordan','Descripcion de Jordan'),
(115, 'Kazakhstan','Descripcion de Kazakhstan'),
(116, 'Kenya','Descripcion de Kenya'),
(117, 'Kiribati','Descripcion de Kiribati'),
(118, 'Korea, Democratic People\'s Republic of','Descripcion de Korea, Democratic People\'s Republic of'),
(119, 'Korea, Republic of','Descripcion de Korea, Republic of'),
(120, 'Kosovo','Descripcion de Kosovo'),
(121, 'Kuwait','Descripcion de Kuwait'),
(122, 'Kyrgyzstan','Descripcion de Kyrgyzstan'),
(123, 'Lao People\'s Democratic Republic','Descripcion de Lao People\'s Democratic Republic'),
(124, 'Latvia','Descripcion de Latvia'),
(125, 'Lebanon','Descripcion de Lebanon'),
(126, 'Lesotho','Descripcion de Lesotho'),
(127, 'Liberia','Descripcion de Liberia'),
(128, 'Libyan Arab Jamahiriya','Descripcion de Libyan Arab Jamahiriya'),
(129, 'Liechtenstein','Descripcion de Liechtenstein'),
(130, 'Lithuania','Descripcion de Lithuania'),
(131, 'Luxembourg','Descripcion de Luxembourg'),
(132, 'Macao','Descripcion de Macao'),
(133, 'Macedonia, the Former Yugoslav Republic of','Descripcion de Macedonia, the Former Yugoslav Republic of'),
(134, 'Madagascar','Descripcion de Madagascar'),
(135, 'Malawi','Descripcion de Malawi'),
(136, 'Malaysia','Descripcion de Malaysia'),
(137, 'Maldives','Descripcion de Maldives'),
(138, 'Mali','Descripcion de Mali'),
(139, 'Malta','Descripcion de Malta'),
(140, 'Marshall Islands','Descripcion de Marshall Islands'),
(141, 'Martinique','Descripcion de Martinique'),
(142, 'Mauritania','Descripcion de Mauritania'),
(143, 'Mauritius','Descripcion de Mauritius'),
(144, 'Mayotte','Descripcion de Mayotte'),
(145, 'Mexico','Descripcion de Mexico'),
(146, 'Micronesia, Federated States of','Descripcion de Micronesia, Federated States of'),
(147, 'Moldova, Republic of','Descripcion de Moldova, Republic of'),
(148, 'Monaco','Descripcion de Monaco'),
(149, 'Mongolia','Descripcion de Mongolia'),
(150, 'Montenegro','Descripcion de Montenegro'),
(151, 'Montserrat','Descripcion de Montserrat'),
(152, 'Morocco','Descripcion de Morocco'),
(153, 'Mozambique','Descripcion de Mozambique'),
(154, 'Myanmar','Descripcion de Myanmar'),
(155, 'Namibia','Descripcion de Namibia'),
(156, 'Nauru','Descripcion de Nauru'),
(157, 'Nepal','Descripcion de Nepal'),
(158, 'Netherlands','Descripcion de Netherlands'),
(159, 'Netherlands Antilles','Descripcion de Netherlands Antilles'),
(160, 'New Caledonia','Descripcion de New Caledonia'),
(161, 'New Zealand','Descripcion de New Zealand'),
(162, 'Nicaragua','Descripcion de Nicaragua'),
(163, 'Niger','Descripcion de Niger'),
(164, 'Nigeria','Descripcion de Nigeria'),
(165, 'Niue','Descripcion de Niue'),
(166, 'Norfolk Island','Descripcion de Norfolk Island'),
(167, 'Northern Mariana Islands','Descripcion de Northern Mariana Islands'),
(168, 'Norway','Descripcion de Norway'),
(169, 'Oman','Descripcion de Oman'),
(170, 'Pakistan','Descripcion de Pakistan'),
(171, 'Palau','Descripcion de Palau'),
(172, 'Palestinian Territory, Occupied','Descripcion de Palestinian Territory, Occupied'),
(173, 'Panama','Descripcion de Panama'),
(174, 'Papua New Guinea','Descripcion de Papua New Guinea'),
(175, 'Paraguay','Descripcion de Paraguay'),
(176, 'Peru','Descripcion de Peru'),
(177, 'Philippines','Descripcion de Philippines'),
(178, 'Pitcairn','Descripcion de Pitcairn'),
(179, 'Poland','Descripcion de Poland'),
(180, 'Portugal','Descripcion de Portugal'),
(181, 'Puerto Rico','Descripcion de Puerto Rico'),
(182, 'Qatar','Descripcion de Qatar'),
(183, 'Reunion','Descripcion de Reunion'),
(184, 'Romania','Descripcion de Romania'),
(185, 'Russian Federation','Descripcion de Russian Federation'),
(186, 'Rwanda','Descripcion de Rwanda'),
(187, 'Saint Barthelemy','Descripcion de Saint Barthelemy'),
(188, 'Saint Helena','Descripcion de Saint Helena'),
(189, 'Saint Kitts and Nevis','Descripcion de Saint Kitts and Nevis'),
(190, 'Saint Lucia','Descripcion de Saint Lucia'),
(191, 'Saint Martin','Descripcion de Saint Martin'),
(192, 'Saint Pierre and Miquelon','Descripcion de Saint Pierre and Miquelon'),
(193, 'Saint Vincent and the Grenadines','Descripcion de Saint Vincent and the Grenadines'),
(194, 'Samoa','Descripcion de Samoa'),
(195, 'San Marino','Descripcion de San Marino'),
(196, 'Sao Tome and Principe','Descripcion de Sao Tome and Principe'),
(197, 'Saudi Arabia','Descripcion de Saudi Arabia'),
(198, 'Senegal','Descripcion de Senegal'),
(199, 'Serbia','Descripcion de Serbia'),
(200, 'Serbia and Montenegro','Descripcion de Serbia and Montenegro'),
(201, 'Seychelles','Descripcion de Seychelles'),
(202, 'Sierra Leone','Descripcion de Sierra Leone'),
(203, 'Singapore','Descripcion de Singapore'),
(204, 'Sint Maarten','Descripcion de Sint Maarten'),
(205, 'Slovakia','Descripcion de Slovakia'),
(206, 'Slovenia','Descripcion de Slovenia'),
(207, 'Solomon Islands','Descripcion de Solomon Islands'),
(208, 'Somalia','Descripcion de Somalia'),
(209, 'South Africa','Descripcion de South Africa'),
(210, 'South Georgia and the South Sandwich Islands','Descripcion de South Georgia and the South Sandwich Islands'),
(211, 'South Sudan','Descripcion de South Sudan'),
(212, 'Spain','Descripcion de Spain'),
(213, 'Sri Lanka','Descripcion de Sri Lanka'),
(214, 'Sudan','Descripcion de Sudan'),
(215, 'Suriname','Descripcion de Suriname'),
(216, 'Svalbard and Jan Mayen','Descripcion de Svalbard and Jan Mayen'),
(217, 'Swaziland','Descripcion de Swaziland'),
(218, 'Sweden','Descripcion de Sweden'),
(219, 'Switzerland','Descripcion de Switzerland'),
(220, 'Syrian Arab Republic','Descripcion de Syrian Arab Republic'),
(221, 'Taiwan, Province of China','Descripcion de Taiwan, Province of China'),
(222, 'Tajikistan','Descripcion de Tajikistan'),
(223, 'Tanzania, United Republic of','Descripcion de Tanzania, United Republic of'),
(224, 'Thailand','Descripcion de Thailand'),
(225, 'Timor-Leste','Descripcion de Timor-Leste'),
(226, 'Togo','Descripcion de Togo'),
(227, 'Tokelau','Descripcion de Tokelau'),
(228, 'Tonga','Descripcion de Tonga'),
(229, 'Trinidad and Tobago','Descripcion de Trinidad and Tobago'),
(230, 'Tunisia','Descripcion de Tunisia'),
(231, 'Turkey','Descripcion de Turkey'),
(232, 'Turkmenistan','Descripcion de Turkmenistan'),
(233, 'Turks and Caicos Islands','Descripcion de Turks and Caicos Islands'),
(234, 'Tuvalu','Descripcion de Tuvalu'),
(235, 'Uganda','Descripcion de Uganda'),
(236, 'Ukraine','Descripcion de Ukraine'),
(237, 'United Arab Emirates','Descripcion de United Arab Emirates'),
(238, 'United Kingdom','Descripcion de United Kingdom'),
(239, 'United States','Descripcion de United States'),
(240, 'United States Minor Outlying Islands','Descripcion de United States Minor Outlying Islands'),
(241, 'Uruguay','Descripcion de Uruguay'),
(242, 'Uzbekistan','Descripcion de Uzbekistan'),
(243, 'Vanuatu','Descripcion de Vanuatu'),
(244, 'Venezuela','Descripcion de Venezuela'),
(245, 'Viet Nam','Descripcion de Viet Nam'),
(246, 'Virgin Islands, British','Descripcion de Virgin Islands, British'),
(247, 'Virgin Islands, U.s.','Descripcion de Virgin Islands, U.s.'),
(248, 'Wallis and Futuna','Descripcion de Wallis and Futuna'),
(249, 'Western Sahara','Descripcion de Western Sahara'),
(250, 'Yemen','Descripcion de Yemen'),
(251, 'Zambia','Descripcion de Zambia'),
(252, 'Zimbabwe','Descripcion de Zimbabwe');
