version: "3.7"
services:
  rabbitmq:
    restart: unless-stopped
    image: rabbitmq:3.8-management
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./data/rmq/data:/var/lib/rabbitmq/
      - ./data/rmq/log:/var/log/rabbitmq/
    networks:
      - rabbitmq_net

networks:
  rabbitmq_net:
    driver: bridge
