export const PayloadActions = {
  AUTH: {
    LOGIN: 'AUTH__LOGIN',
    LOGOUT: 'AUTH__LOGOUT',
    REFRESH: 'AUTH__REFRESH',
    CHECK: 'AUTH__CHECK',
  },
  USERS: {
    CREATE: 'USERS__CREATE',
    UPDATE: 'USERS__UPDATE',
    DELETE: 'USERS__DELETE',
    FIND_ALL: 'USERS__FIND_ALL',
    FIND_BY_ID: 'USERS__FIND_BY_ID',
    FIND_BY_USERNAME: 'USERS__FIND_BY_USERNAME',
  },
  PARTIES: {
    FIND_ALL: 'PARTIES__FIND_ALL',
    FIND_BY_ID: 'PARTIES__FIND_BY_ID',
    CREATE: 'PARTIES__CREATE',
    JOIN: 'PARTIES__JOIN',
    DELETE: 'PARTIES__DELETE',
    UPDATE: 'PARTIES__UPDATE',
  },
  MAIL: {
    SEND_SIGNUP_WELCOME: 'MAILER__SEND_SIGNUP_WELCOME',
    SEND_MANY: 'MAILER__SEND_MANY',
  },
  IMAGES: {
    CREATE: 'IMAGE__CREATE',
    UPDATE: 'IMAGE__UPDATE',
  },
  TRIPS: {
    TRIPS: {
      CREATE: 'TRIPS__CREATE',
      UPDATE: 'TRIPS__UPDATE',
      DELETE: 'TRIPS__DELETE',
      FIND_ALL: 'TRIPS__FIND_ALL',
      FIND_BY_ID: 'TRIPS__FIND_BY_ID',
    },
    TRANSPORTS: {
      CREATE: 'TRANSPORTS__CREATE',
      UPDATE: 'TRANSPORTS__UPDATE',
      DELETE: 'TRANSPORTS__DELETE',
      FIND_ALL: 'TRANSPORTS__FIND_ALL',
      FIND_BY_ID: 'TRANSPORTS__FIND_BY_ID',
    },
    HOTELS: {
      CREATE: 'HOTELS__CREATE',
      UPDATE: 'HOTELS__UPDATE',
      DELETE: 'HOTELS__DELETE',
      FIND_ALL: 'HOTELS__FIND_ALL',
      FIND_BY_ID: 'HOTELS__FIND_BY_ID',
    },
    DESTINATIONS: {
      CREATE: 'DESTINATIONS__CREATE',
      UPDATE: 'DESTINATIONS__UPDATE',
      DELETE: 'DESTINATIONS__DELETE',
      FIND_ALL: 'DESTINATIONS__FIND_ALL',
      FIND_BY_ID: 'DESTINATIONS__FIND_BY_ID',
    },
  },
};
