---
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel previous integration
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.access_token }}
      - uses: actions/checkout@v2
        with:
          fetch_depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Install deps
        run: npm ci
      - name: Run tests
        run: npm run test:all
name: Testing
'on':
  push:
    branches:
      - main
